### ISSUE TITLE
TODO: 2024-01-10

### ISSUE THREAD

**Issue by Jinjin89** [Jinjin89/pipeline#1]
# Common
- [ ]  wirte common python/R function for extracting/preprocess data
- [ ] generate the new directory, stores all the processed data(which is human-readable, analysis-ready),consider the project-oriented or sample-oriented
- [x] consider 1) wirte all RNA script file into one snakemake, 2) remove rule all file, 3) control the pipline using output file, like, mRNA.done, star_fusion.done, etc
